subdir-y += lib

obj-y += entry.o

obj-y += traps.o
obj-y += domain.o
obj-y += vfp.o
obj-y += smpboot.o
obj-y += domctl.o
obj-y += cache.o
obj-y += insn.o

obj-$(EARLY_PRINTK) += debug.o
obj-$(CONFIG_XSPLICE) += xsplice.o
